package swingmenus.multiplayer;

import commands.mainmenucommands.HostGameCommand;
import commands.mainmenucommands.JoinGameCommand;
import swingmenus.multiplayer.data.MultiplayerLobbyData;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 * Created by Max on 3/22/2015.
 */
public class MultiplayerLobby {
    private JPanel mainView;
    private JList GameList;
    private JButton joinGameButton;
    private JButton hostAGameButton;
    private JButton enterServerInfoButton;
    private JCheckBox useDefaultCheckBox;
    private JTextField playerNameTextField;
    private JFrame frame;
    private String serverAddress = "127.0.0.1";
    private int serverPort = 51234;
    private MultiplayerLobbyData data;
    private JoinGameCommand joinGameCommand;

    public MultiplayerLobby(final JFrame frame) {
        this.frame = frame;
        this.data = new MultiplayerLobbyData(this);
        joinGameCommand = new JoinGameCommand(frame, data);
        data.setServerIPAddress("127.0.0.1");
        data.setServerPortNumber(serverPort);
        this.setUseDefaultCheckBoxChecked(true);

        joinGameButton.setAction(joinGameCommand);
        hostAGameButton.setAction(new HostGameCommand(frame, data));
        useDefaultCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (useDefaultCheckBox.isSelected()) {
                    data.setServerIPAddress("127.0.0.1");
                    data.setServerPortNumber(serverPort);
                }
            }
        });

        enterServerInfoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ServerInfoDialog dialog = new ServerInfoDialog(data);
                dialog.setSize(500, 300);
                dialog.setVisible(true);
            }
        });
        playerNameTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                data.setPlayerName(playerNameTextField.getText());
            }
        });
    }

    public void setUseDefaultCheckBoxChecked(boolean checked) {
        this.useDefaultCheckBox.setSelected(checked);
    }

    public JPanel getMainView() {
        return mainView;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainView = new JPanel();
        mainView.setLayout(new BorderLayout(0, 0));
        GameList = new JList();
        mainView.add(GameList, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        mainView.add(panel1, BorderLayout.SOUTH);
        joinGameButton = new JButton();
        joinGameButton.setEnabled(true);
        joinGameButton.setText("Join Game");
        joinGameButton.setToolTipText("Select a game before clicking this.");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(joinGameButton, gbc);
        hostAGameButton = new JButton();
        hostAGameButton.setText("Host a Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(hostAGameButton, gbc);
        enterServerInfoButton = new JButton();
        enterServerInfoButton.setText("Enter Server Info");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(enterServerInfoButton, gbc);
        useDefaultCheckBox = new JCheckBox();
        useDefaultCheckBox.setSelected(true);
        useDefaultCheckBox.setText("Use Default Local 127.0.0.1:51234");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(useDefaultCheckBox, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        mainView.add(panel2, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel3, gbc);
        playerNameTextField = new JTextField();
        playerNameTextField.setText("Default Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.7;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 50);
        panel3.add(playerNameTextField, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(4);
        label1.setText("Player Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel3.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setHorizontalTextPosition(0);
        label2.setText("Multiplayer Lobby");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel2.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainView;
    }
}
