package a3;

import commands.mainMenuCommands.SwitchToMultiPlayerCommand;
import commands.mainMenuCommands.SwitchToSinglePlayerCommand;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Max on 3/22/2015.
 */
public class StartGame {
    private JPanel mainView;
    private JButton singlePlayerButton;
    private JButton multiPlayerButton;
    private static JFrame frame;

    public static void main(String[] args) {
        frame = new JFrame("Maze Game");
        frame.setContentPane(new StartGame().mainView);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.setSize(1000, 500);
        frame.setVisible(true);
    }

    public StartGame() {
        mainView.setVisible(true);
        multiPlayerButton.setAction(new SwitchToMultiPlayerCommand(frame));
        singlePlayerButton.setAction(new SwitchToSinglePlayerCommand(frame));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainView = new JPanel();
        mainView.setLayout(new BorderLayout(0, 0));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setText("Maze Game");
        mainView.add(label1, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainView.add(panel1, BorderLayout.SOUTH);
        singlePlayerButton = new JButton();
        singlePlayerButton.setText("Single Player");
        panel1.add(singlePlayerButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        multiPlayerButton = new JButton();
        multiPlayerButton.setText("Multi Player");
        panel1.add(multiPlayerButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainView;
    }
}
